#!/usr/bin/env python3
"""
Export a compact, line-numbered repository context file for AI/code review.

Target repo:
    Crystonix/godot_world_lab

Put this file at:
    tools/context/export_repo_context.py

Run from the repository root:
    python tools/context/export_repo_context.py

Default output:
    godot_world_lab-content.txt
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable


DEFAULT_OUTPUT = "godot_world_lab-content.txt"

DEFAULT_EXTENSIONS = {
    ".gd",
    ".tscn",
    ".tres",
    ".godot",
    ".md",
    ".py",
    ".sh",
    ".json",
    ".yaml",
    ".yml",
    ".cfg",
}

DEFAULT_INCLUDED_FILENAMES = {
    "project.godot",
    "Taskfile.yml",
    "taskfile.yml",
    "README",
    "LICENSE",
}

DEFAULT_EXCLUDED_DIRS = {
    ".git",
    ".github",
    ".godot",
    ".import",
    ".vscode",
    ".idea",
    "__pycache__",
    "node_modules",
    "dist",
    "build",
    "target",
}

DEFAULT_EXCLUDED_PATH_PARTS = {
    ("addons", "godot_grid", "bin"),
    ("addons", "godot_world_streaming", "bin"),
}

DEFAULT_EXCLUDED_SUFFIXES = {
    "-content.txt",
}

BINARY_EXTENSIONS = {
    ".dll",
    ".dylib",
    ".exe",
    ".glb",
    ".gltf",
    ".ico",
    ".jpg",
    ".jpeg",
    ".mesh",
    ".mp3",
    ".ogg",
    ".png",
    ".pck",
    ".res",
    ".so",
    ".stex",
    ".svg",
    ".ttf",
    ".wav",
    ".webp",
    ".zip",
}


def has_path_parts(path: Path, parts: tuple[str, ...]) -> bool:
    """Return true when all path parts appear contiguously in the path."""
    path_parts = path.parts
    part_count = len(parts)

    if part_count == 0 or part_count > len(path_parts):
        return False

    for index in range(0, len(path_parts) - part_count + 1):
        if path_parts[index : index + part_count] == parts:
            return True

    return False


def should_skip_path(path: Path, root: Path) -> bool:
    """Return true when a path is generated, binary-heavy, or not useful context."""
    relative_path = path.relative_to(root)

    if any(part in DEFAULT_EXCLUDED_DIRS for part in relative_path.parts):
        return True

    if any(has_path_parts(relative_path, parts) for parts in DEFAULT_EXCLUDED_PATH_PARTS):
        return True

    if any(relative_path.name.endswith(suffix) for suffix in DEFAULT_EXCLUDED_SUFFIXES):
        return True

    if relative_path.suffix.lower() in BINARY_EXTENSIONS:
        return True

    return False


def should_include_file(path: Path, root: Path) -> bool:
    """Return true when a file should be included in the exported AI context."""
    if should_skip_path(path, root):
        return False

    if path.name in DEFAULT_INCLUDED_FILENAMES:
        return True

    return path.suffix.lower() in DEFAULT_EXTENSIONS


def iter_context_files(root: Path) -> Iterable[Path]:
    """Yield all included context files in stable repository order."""
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue

        if should_include_file(path, root):
            yield path


def read_text_lossy(path: Path) -> str:
    """Read a text file while tolerating occasional non-UTF8 bytes."""
    return path.read_text(encoding="utf-8", errors="replace")


def write_context_file(root: Path, output_path: Path) -> int:
    """Write one line-numbered context file and return the number of included files."""
    files = list(iter_context_files(root))

    with output_path.open("w", encoding="utf-8", newline="\n") as output:
        output.write("# godot_world_lab repository context\n")
        output.write("# Generated by tools/context/export_repo_context.py\n")
        output.write("# Format: file sections with 1-based line numbers.\n\n")

        for file_index, path in enumerate(files):
            relative_path = path.relative_to(root).as_posix()
            text = read_text_lossy(path)
            lines = text.splitlines()

            if file_index > 0:
                output.write("\n\n")

            output.write(f"===== FILE: {relative_path} =====\n")

            if not lines:
                output.write("0001 | \n")
                continue

            for line_number, line in enumerate(lines, start=1):
                output.write(f"{line_number:04d} | {line}\n")

    return len(files)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for the context exporter."""
    parser = argparse.ArgumentParser(
        description="Export godot_world_lab source files into one line-numbered AI context file.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Repository root. Defaults to the current working directory.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=f"Output file. Defaults to ./{DEFAULT_OUTPUT}.",
    )
    return parser.parse_args()


def main() -> int:
    """CLI entrypoint."""
    args = parse_args()

    root = args.root.resolve()
    output_path = (args.output or root / DEFAULT_OUTPUT).resolve()

    if not root.exists():
        raise SystemExit(f"Repository root does not exist: {root}")

    if not root.is_dir():
        raise SystemExit(f"Repository root is not a directory: {root}")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    included_count = write_context_file(root=root, output_path=output_path)

    print(f"Exported {included_count} files to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
